# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecordMunged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dns_records_munged',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdnsZoneXfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=255)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pdns_zone_xfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordMunged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records_munged',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DhcpDnsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.IntegerField(blank=True, default=-1, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dhcp_dns_records',
            },
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={b'blank': b'Name fields for DNS records cannot be blank.'}, max_length=255)),
                ('text_content', models.CharField(blank=True, max_length=255, null=True)),
                ('ttl', models.IntegerField(blank=True, default=14400, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name=b'Priority')),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('dns_type', 'name'),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'dns_records',
                'verbose_name': 'DNS Record',
            },
        ),
        migrations.CreateModel(
            name='DnsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'dns_types',
                'verbose_name': 'DNS Type',
                'permissions': (('add_records_to_dnstype', 'Can add records to'),),
            },
        ),
        migrations.CreateModel(
            name='DnsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dns_views',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('master', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_check', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=6)),
                ('notified_serial', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'domains',
                'permissions': (('is_owner_domain', 'Is owner'), ('add_records_to_domain', 'Can add records to')),
            },
        ),
        migrations.CreateModel(
            name='Supermaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('nameserver', models.CharField(max_length=255)),
                ('account', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'supermasters',
            },
        ),
    ]
