# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRecordMunged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dns_records_munged',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PdnsZoneXfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=255)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pdns_zone_xfer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecordMunged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('prio', models.IntegerField(blank=True, null=True)),
                ('change_date', models.IntegerField(blank=True, null=True)),
                ('view_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'records_munged',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DhcpDnsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.IntegerField(blank=True, default=-1, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dhcp_dns_records',
            },
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={b'blank': b'Name fields for DNS records cannot be blank.'}, max_length=255)),
                ('text_content', models.CharField(blank=True, max_length=255, null=True)),
                ('ttl', models.IntegerField(blank=True, default=14400, null=True)),
                ('priority', models.IntegerField(blank=True, null=True, verbose_name=b'Priority')),
                ('host', models.ForeignKey('hosts.Host', db_column='mac', to_field='mac')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('dns_type', 'name'),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'dns_records',
                'verbose_name': 'DNS Record',
            },
        ),
        migrations.CreateModel(
            name='DnsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_permissions', models.ForeignKey(db_column=b'min_permissions', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='user.Permission')),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'dns_types',
                'verbose_name': 'DNS Type',
                'permissions': (('add_records_to_dnstype', 'Can add records to'),),
            },
        ),
        migrations.CreateModel(
            name='DnsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dns_views',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('master', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_check', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(max_length=6)),
                ('notified_serial', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domains',
                'permissions': (('is_owner_domain', 'Is owner'), ('add_records_to_domain', 'Can add records to')),
            },
        ),
        migrations.CreateModel(
            name='Supermaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=25)),
                ('nameserver', models.CharField(max_length=255)),
                ('account', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supermasters',
            },
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='dns_type',
            field=models.ForeignKey(db_column=b'tid', error_messages={b'blank': b'Type fields for DNS records cannot be blank.'}, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.DnsType', verbose_name=b'Type'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='dns_view',
            field=models.ForeignKey(blank=True, db_column=b'vid', null=True, on_delete=django.db.models.deletion.CASCADE, to='dns.DnsView', verbose_name=b'View'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='domain',
            field=models.ForeignKey(db_column=b'did', on_delete=django.db.models.deletion.CASCADE, to='dns.Domain', verbose_name=b'Domain'),
        ),
    ]
