# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns', '0001_initial'),
        ('hosts', '0001_initial'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermaster',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='domain',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dnstype',
            name='min_permissions',
            field=models.ForeignKey(db_column=b'min_permissions', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='user.Permission'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='dns_type',
            field=models.ForeignKey(db_column=b'tid', error_messages={b'blank': b'Type fields for DNS records cannot be blank.'}, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.DnsType', verbose_name=b'Type'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='dns_view',
            field=models.ForeignKey(blank=True, db_column=b'vid', null=True, on_delete=django.db.models.deletion.CASCADE, to='dns.DnsView', verbose_name=b'View'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='domain',
            field=models.ForeignKey(db_column=b'did', on_delete=django.db.models.deletion.CASCADE, to='dns.Domain', verbose_name=b'Domain'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='host',
            field=models.ForeignKey(blank=True, db_column=b'mac', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='hosts.Host', to_field=b'mac'),
        ),
        migrations.AddField(
            model_name='dnsrecord',
            name='ip_content',
            field=models.ForeignKey(blank=True, db_column=b'ip_content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arecords', to='network.Address', verbose_name=b'IP Content'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='did',
            field=models.ForeignKey(db_column=b'did', on_delete=django.db.models.deletion.CASCADE, to='dns.Domain'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='ip_content',
            field=models.ForeignKey(blank=True, db_column=b'ip_content', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Address'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='name',
            field=models.OneToOneField(db_column=b'name', on_delete=django.db.models.deletion.CASCADE, to='hosts.Host', to_field=b'hostname'),
        ),
    ]
