# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns', '0001_initial'),
        ('hosts', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsrecord',
            name='ip_content',
            field=models.ForeignKey(blank=True, db_column=b'ip_content', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arecords', to='network.Address', verbose_name=b'IP Content'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='did',
            field=models.ForeignKey(db_column=b'did', on_delete=django.db.models.deletion.CASCADE, to='dns.Domain'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='ip_content',
            field=models.ForeignKey(blank=True, db_column=b'ip_content', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Address'),
        ),
        migrations.AddField(
            model_name='dhcpdnsrecord',
            name='name',
            field=models.OneToOneField(db_column=b'name', on_delete=django.db.models.deletion.CASCADE, to='hosts.Host', to_field=b'hostname'),
        ),
    ]
