# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("dns", "0005_auto_20150218_1327")]

    operations = [
        migrations.AlterModelOptions(
            name="dnsrecord",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("dns_type", "name"),
                "verbose_name": "DNS Record",
            },
        ),
        migrations.AlterField(
            model_name="dhcpdnsrecord",
            name="name",
            field=models.OneToOneField(
                db_column=b"name",
                on_delete=django.db.models.deletion.CASCADE,
                to="hosts.Host",
                to_field=b"hostname",
            ),
        ),
    ]
