# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields
import netfields.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('hosts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', netfields.fields.InetAddressField(max_length=39, primary_key=True, serialize=False)),
                ('reserved', models.BooleanField(default=False)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'addresses',
                'verbose_name_plural': 'addresses',
            },
        ),

        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'addresstypes',
            },
        ),
        migrations.CreateModel(
            name='DefaultPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', netfields.fields.CidrAddressField(max_length=43, unique=True)),
            ],
            options={
                'db_table': 'default_pools',
            },
        ),
        migrations.CreateModel(
            name='DhcpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dhcp_groups',
                'verbose_name': 'DHCP group',
            },
        ),
        migrations.CreateModel(
            name='DhcpOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('option', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dhcp_options',
                'verbose_name': 'DHCP option',
            },
        ),
        migrations.CreateModel(
            name='DhcpOptionToDhcpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BinaryField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, db_column=b'gid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='network.DhcpGroup')),
                ('option', models.ForeignKey(blank=True, db_column=b'oid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_values', to='network.DhcpOption')),
            ],
            options={
                'db_table': 'dhcp_options_to_dhcp_groups',
            },
        ),
        migrations.CreateModel(
            name='HostToPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(db_column=b'mac', to_field='mac', on_delete=django.db.models.deletion.CASCADE, related_name='host_pools', to='hosts.Host')),
            ],
            options={
                'db_table': 'hosts_to_pools',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('network', netfields.fields.CidrAddressField(max_length=43, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway', netfields.fields.InetAddressField(blank=True, max_length=39, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default=b'', editable=False, null=True, serialize=False)),
            ],
            options={
                'ordering': ('network',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'networks',
                'permissions': (('is_owner_network', 'Is owner'), ('add_records_to_network', 'Can add records to')),
            },
        ),
        migrations.CreateModel(
            name='NetworkRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', netfields.fields.CidrAddressField(max_length=43, unique=True)),
            ],
            options={
                'db_table': 'network_ranges',
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('allow_unknown', models.BooleanField(default=False)),
                ('lease_time', models.IntegerField()),
                ('assignable', models.BooleanField(default=False)),
                ('dhcp_group', models.ForeignKey(blank=True, db_column=b'dhcp_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.DhcpGroup')),
            ],
            options={
                'db_table': 'pools',
                'permissions': (('add_records_to_pool', 'Can add records to'),),
            },
        ),
        migrations.CreateModel(
            name='SharedNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_networks',
            },
        ),
        migrations.CreateModel(
            name='TaggedNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changed', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vlans',
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('address', models.OneToOneField(db_column=b'address', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leases', serialize=False, to='network.Address')),
                ('abandoned', models.BooleanField(default=False)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('host', models.ForeignKey(db_column=b'mac', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='hosts.Host')),
            ],
            options={
                'db_table': 'leases',
            },
        ),
        migrations.CreateModel(
            name='NetworkToVlan',
            fields=[
                ('network', models.OneToOneField(db_column=b'network', to_field='network', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='network.Network')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vlan', models.ForeignKey(db_column=b'vlan', on_delete=django.db.models.deletion.CASCADE, to='network.Vlan')),
            ],
            options={
                'db_table': 'networks_to_vlans',
            },
        ),
        migrations.AddField(
            model_name='taggednetworks',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Network', to_field='network'),
        ),
        migrations.AddField(
            model_name='taggednetworks',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_taggednetworks_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='network',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='dhcp_group',
            field=models.ForeignKey(blank=True, db_column=b'dhcp_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.DhcpGroup'),
        ),
        migrations.AddField(
            model_name='network',
            name='shared_network',
            field=models.ForeignKey(blank=True, db_column=b'shared_network', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.SharedNetwork'),
        ),
        migrations.AddField(
            model_name='network',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='network.TaggedNetworks', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='hosttopool',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_pools', to='network.Pool'),
        ),
        migrations.AddField(
            model_name='dhcpgroup',
            name='dhcp_options',
            field=models.ManyToManyField(through='network.DhcpOptionToDhcpGroup', to='network.DhcpOption'),
        ),
        migrations.AddField(
            model_name='defaultpool',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_defaults', to='network.Pool'),
        ),
        migrations.AddField(
            model_name='addresstype',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Pool'),
        ),
        migrations.AddField(
            model_name='addresstype',
            name='ranges',
            field=models.ManyToManyField(related_name='address_ranges', to='network.NetworkRange'),
        ),
        migrations.AddField(
            model_name='address',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='host',
            field=models.ForeignKey(blank=True, db_column=b'mac', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='hosts.Host'),
        ),
        migrations.AddField(
            model_name='address',
            name='network',
            field=models.ForeignKey(db_column=b'network', on_delete=django.db.models.deletion.CASCADE, related_name='net_addresses', to='network.Network'),
        ),
        migrations.AddField(
            model_name='address',
            name='pool',
            field=models.ForeignKey(blank=True, db_column=b'pool', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.Pool'),
        ),
        migrations.AddField(
            model_name='network',
            name='vlans',
            field=models.ManyToManyField(related_name='vlan_networks', through='network.NetworkToVlan', to='network.Vlan'),
        ),
    ]
