# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 21:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0002_auto_20161202_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taggednetworks',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Network'),
        ),
        migrations.AddField(
            model_name='taggednetworks',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_taggednetworks_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='sharednetwork',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pool',
            name='dhcp_group',
            field=models.ForeignKey(blank=True, db_column=b'dhcp_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.DhcpGroup'),
        ),
        migrations.AddField(
            model_name='network',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='network',
            name='dhcp_group',
            field=models.ForeignKey(blank=True, db_column=b'dhcp_group', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.DhcpGroup'),
        ),
        migrations.AddField(
            model_name='network',
            name='shared_network',
            field=models.ForeignKey(blank=True, db_column=b'shared_network', null=True, on_delete=django.db.models.deletion.CASCADE, to='network.SharedNetwork'),
        ),
        migrations.AddField(
            model_name='network',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='network.TaggedNetworks', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='hosttopool',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hosttopool',
            name='host',
            field=models.ForeignKey(db_column=b'mac', on_delete=django.db.models.deletion.CASCADE, related_name='host_pools', to='hosts.Host', to_field=b'mac'),
        ),
        migrations.AddField(
            model_name='hosttopool',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_pools', to='network.Pool'),
        ),
        migrations.AddField(
            model_name='dhcpoptiontodhcpgroup',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dhcpoptiontodhcpgroup',
            name='group',
            field=models.ForeignKey(blank=True, db_column=b'gid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_values', to='network.DhcpGroup'),
        ),
        migrations.AddField(
            model_name='dhcpoptiontodhcpgroup',
            name='option',
            field=models.ForeignKey(blank=True, db_column=b'oid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_values', to='network.DhcpOption'),
        ),
        migrations.AddField(
            model_name='dhcpgroup',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dhcpgroup',
            name='dhcp_options',
            field=models.ManyToManyField(through='network.DhcpOptionToDhcpGroup', to='network.DhcpOption'),
        ),
        migrations.AddField(
            model_name='defaultpool',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_defaults', to='network.Pool'),
        ),
        migrations.AddField(
            model_name='addresstype',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Pool'),
        ),
        migrations.AddField(
            model_name='addresstype',
            name='ranges',
            field=models.ManyToManyField(related_name='address_ranges', to='network.NetworkRange'),
        ),
        migrations.AddField(
            model_name='address',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='host',
            field=models.ForeignKey(blank=True, db_column=b'mac', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='hosts.Host', to_field=b'mac'),
        ),
        migrations.AddField(
            model_name='address',
            name='network',
            field=models.ForeignKey(db_column=b'network', on_delete=django.db.models.deletion.CASCADE, related_name='net_addresses', to='network.Network', to_field=b'network'),
        ),
        migrations.AddField(
            model_name='address',
            name='pool',
            field=models.ForeignKey(blank=True, db_column=b'pool', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.Pool'),
        ),
        migrations.AddField(
            model_name='networktovlan',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networktovlan',
            name='vlan',
            field=models.ForeignKey(db_column=b'vlan', on_delete=django.db.models.deletion.CASCADE, to='network.Vlan'),
        ),
        migrations.AddField(
            model_name='network',
            name='vlans',
            field=models.ManyToManyField(related_name='vlan_networks', through='network.NetworkToVlan', to='network.Vlan'),
        ),
        migrations.AddField(
            model_name='lease',
            name='host',
            field=models.ForeignKey(db_column=b'mac', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='hosts.Host', to_field=b'mac'),
        ),
    ]
