# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-16 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("network", "0006_auto_20170324_1644"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(max_length=255, unique=True)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        db_column="changed_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "buildings"},
        ),
        migrations.CreateModel(
            name="BuildingToVlan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tagged", models.BooleanField(default=False)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        db_column="building",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.Building",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        db_column="changed_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "buildings_to_vlans"},
        ),
        migrations.AddField(
            model_name="vlan",
            name="vlan_id",
            field=models.SmallIntegerField(default="1"),
            preserve_default=False,
        ),
        migrations.RunSQL(sql=["UPDATE vlans SET vlan_id = id"]),
        migrations.AlterField(
            model_name="addresstype",
            name="ranges",
            field=models.ManyToManyField(
                blank=True, related_name="address_ranges", to="network.NetworkRange"
            ),
        ),
        migrations.AlterField(
            model_name="vlan", name="changed", field=models.DateTimeField(auto_now=True)
        ),
        migrations.AlterField(
            model_name="vlan",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE vlans DROP CONSTRAINT vlans_id_check",
                "ALTER TABLE vlans ADD CONSTRAINT vlans_id_check CHECK (vlan_id > 0 AND vlan_id < 4096)",
                "ALTER SEQUENCE vlans_id_seq RESTART WITH 5000",
            ],
            reverse_sql=[
                "ALTER TABLE vlans DROP CONSTRAINT vlans_id_check",
                "ALTER TABLE vlans ADD CONSTRAINT vlans_id_check CHECK (id > 0 AND id < 4096)",
                "ALTER TABLE vlans ALTER COLUMN id DROP DEFAULT",
                "DROP SEQUENCE vlans_id_seq",
            ],
        ),
        migrations.AddField(
            model_name="buildingtovlan",
            name="vlan",
            field=models.ForeignKey(
                db_column="vlan",
                on_delete=django.db.models.deletion.CASCADE,
                to="network.Vlan",
            ),
        ),
        migrations.AddField(
            model_name="vlan",
            name="buildings",
            field=models.ManyToManyField(
                related_name="building_vlans",
                through="network.BuildingToVlan",
                to="network.Building",
            ),
        ),
    ]
