# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-23 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("network", "0007_auto_20190716_1623")]

    operations = [
        migrations.AlterField(
            model_name="vlan",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="buildingtovlan", unique_together=set([("building", "vlan")])
        ),
    ]
