# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("network", "0009_auto_20170925_1250")]

    operations = [
        migrations.AddField(
            model_name="building",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
