# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-25 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("network", "0010_building_name")]

    operations = [
        migrations.RenameField(
            model_name="building", old_name="building_number", new_name="number"
        ),
        migrations.AddField(
            model_name="building",
            name="abbreviation",
            field=models.CharField(default="1", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
