# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("network", "0012_auto_20170925_1627")]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        )
    ]
