# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20171002_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
