# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-05 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("network", "0015_building_city")]

    operations = [
        migrations.AddField(
            model_name="buildingtovlan",
            name="tagegd",
            field=models.BooleanField(default=False),
        )
    ]
