# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("network", "0016_buildingtovlan_tagegd")]

    operations = [
        migrations.RenameField(
            model_name="buildingtovlan", old_name="tagegd", new_name="tagged"
        )
    ]
