# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields
import netfields.fields
import openipam.core.mixins
import openipam.hosts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.IntegerField(blank=True, db_column=b'aid', null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('structured', models.BooleanField(default=None)),
                ('required', models.BooleanField(default=False)),
                ('mac', netfields.fields.MACAddressField(blank=True, null=True)),
                ('avid', models.IntegerField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attributes_to_hosts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('structured', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('validation', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='Disabled',
            fields=[
                ('mac', netfields.fields.MACAddressField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True, db_column=b'disabled')),
            ],
            options={
                'ordering': ('-changed',),
                'db_table': 'disabled',
                'verbose_name': 'Disabled Host',
            },
        ),
        migrations.CreateModel(
            name='ExpirationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'ordering': ('expiration',),
                'db_table': 'expiration_types',
                'permissions': (('is_owner_expiration_type', 'Is owner'),),
            },
        ),
        migrations.CreateModel(
            name='FreeformAttributeToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'freeform_attributes_to_hosts',
            },
        ),
        migrations.CreateModel(
            name='GuestTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255, unique=True)),
                ('starts', models.DateTimeField()),
                ('ends', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'guest_tickets',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', netfields.fields.MACAddressField(unique=True, serialize=False, verbose_name=b'Mac Address')),
                ('hostname', models.CharField(db_index=True, max_length=255, unique=True, validators=[openipam.hosts.validators.validate_hostname])),
                ('description', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField()),
                ('changed', models.DateTimeField(auto_now=True)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default=b'', editable=False, null=True, serialize=False)),
            ],
            options={
                'ordering': ('hostname',),
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'hosts',
                'permissions': (('is_owner_host', 'Is owner'),),
            },
            bases=(openipam.core.mixins.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MacOui',
            fields=[
                ('oui', netfields.fields.MACAddressField(primary_key=True, serialize=False)),
                ('vendor', models.TextField()),
            ],
            options={
                'db_table': 'mac_oui',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.DateField()),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='OUI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', netfields.fields.MACAddressField()),
                ('stop', netfields.fields.MACAddressField()),
                ('shortname', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ouis',
            },
        ),
        migrations.CreateModel(
            name='StructuredAttributeToHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'structured_attributes_to_hosts',
            },
        ),
        migrations.CreateModel(
            name='StructuredAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(db_column=b'aid', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='hosts.Attribute')),
                ('changed_by', models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('attribute__name', 'value'),
                'db_table': 'structured_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='GulRecentArpByaddress',
            fields=[
                ('host', models.OneToOneField(db_column=b'mac', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ip_history', serialize=False, to='hosts.Host')),
                ('stopstamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'gul_recent_arp_byaddress',
            },
        ),
        migrations.CreateModel(
            name='GulRecentArpBymac',
            fields=[
                ('host', models.OneToOneField(db_column=b'mac', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mac_history', serialize=False, to='hosts.Host')),
                ('stopstamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'gul_recent_arp_bymac',
            },
        ),
        migrations.AddField(
            model_name='structuredattributetohost',
            name='host',
            field=models.ForeignKey(db_column=b'mac', on_delete=django.db.models.deletion.CASCADE, related_name='structured_attributes', to='hosts.Host'),
        ),
        migrations.AddField(
            model_name='structuredattributetohost',
            name='structured_attribute_value',
            field=models.ForeignKey(db_column=b'avid', on_delete=django.db.models.deletion.CASCADE, to='hosts.StructuredAttributeValue'),
        ),
    ]
