# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address_type_id',
            field=models.ForeignKey(blank=True, db_column=b'address_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.AddressType'),
        ),
        migrations.AddField(
            model_name='host',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='host',
            name='dhcp_group',
            field=models.ForeignKey(blank=True, db_column=b'dhcp_group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.DhcpGroup', verbose_name=b'DHCP Group'),
        ),
        migrations.AddField(
            model_name='host',
            name='pools',
            field=models.ManyToManyField(related_name='pool_hosts', through='network.HostToPool', to='network.Pool'),
        ),
        migrations.AddField(
            model_name='guestticket',
            name='user',
            field=models.ForeignKey(db_column=b'uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expirationtype',
            name='min_permissions',
            field=models.ForeignKey(db_column=b'min_permissions', db_index=False, on_delete=django.db.models.deletion.CASCADE, to='user.Permission'),
        ),
        migrations.AddField(
            model_name='disabled',
            name='changed_by',
            field=models.ForeignKey(db_column=b'disabled_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attribute',
            name='changed_by',
            field=models.ForeignKey(db_column=b'changed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gulrecentarpbymac',
            name='address',
            field=models.ForeignKey(db_column=b'address', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='mac_history', to='network.Address'),
        ),
        migrations.AddField(
            model_name='gulrecentarpbyaddress',
            name='address',
            field=models.ForeignKey(db_column=b'address', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='ip_history', to='network.Address'),
        ),
    ]
