# Generated by Django 2.2.4 on 2019-08-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("network", "0001_initial"), ("hosts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="gulrecentarpbyaddress",
            name="address",
            field=models.ForeignKey(
                db_column="address",
                db_constraint=False,
                default="127.0.0.1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ip_history",
                to="network.Address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gulrecentarpbymac",
            name="address",
            field=models.ForeignKey(
                db_column="address",
                db_constraint=False,
                default="127.0.0.1",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="mac_history",
                to="network.Address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="host",
            name="address_type_id",
            field=models.ForeignKey(
                blank=True,
                db_column="address_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="network.AddressType",
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="dhcp_group",
            field=models.ForeignKey(
                blank=True,
                db_column="dhcp_group",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="network.DhcpGroup",
                verbose_name="DHCP Group",
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="pools",
            field=models.ManyToManyField(
                related_name="pool_hosts",
                through="network.HostToPool",
                to="network.Pool",
            ),
        ),
    ]
