# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hosts", "0012_auto_20170324_1644")]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="multiple",
            field=models.BooleanField(default=False),
        )
    ]
