# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-12-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0014_auto_20230420_1628"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="admin_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="structuredattributevalue",
            name="admin_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="category",
            field=models.ForeignKey(
                blank=True,
                db_column="category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="hosts.AttributeCategory",
            ),
        ),
    ]
