# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'auth_sources',
            },
        ),
        migrations.CreateModel(
            name='GroupSource',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='source', serialize=False, to='auth.Group')),
                ('source', models.ForeignKey(db_column=b'source', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='user.AuthSource')),
            ],
        ),

        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='min_permissions',
            field=models.ForeignKey(blank=True, db_column=b'min_permissions', db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_min_permissions', to='user.Permission'),
        ),

        migrations.AddField(
            model_name='user',
            name='source',
            field=models.ForeignKey(blank=True, db_column=b'source', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AuthSource'),
        ),

        migrations.RunSQL("BEGIN;\
                            ALTER TABLE permissions ALTER COLUMN id TYPE bit(8) USING(id::bit);\
                            ALTER TABLE users ALTER COLUMN min_permissions TYPE bit(8) USING(min_permissions::bit);\
                           COMMIT;"
        ),
    ]
