# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import openipam.user.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_populate_authsource'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', openipam.user.managers.IPAMUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
